# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85ba24c009d1c9028c60a1d7661f5a03d71bf9413d9bb4fc3db42bd737cc91398e187300306a1720b762317e0f3cf464bee0b8528700d045b37e727089912b0a

test:
  secret_key_base: ea27db0fc67e8fac08ddb4d22348cb405b322544556b96263a3cd8e060758e3f423f428cf03e04e267f07cab5421615199e737956c9a4b16573d4e673f0f5be3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
